[tool.poetry]
name = "glados"
version = "0.1.0"
description = "my personal rutine helper"
authors = ["Valien R. <34721834+rvalien@users.noreply.github.com>"]
license = "MIT License"

[tool.poetry.dependencies]
python = "3.10.5"
aiogram = "^2.20"
asyncpg = "^0.25.0"
aioschedule = "^0.5.2"
gino = "^1.0.1"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
